name: Windows Wheels - Win32 & x64
on: workflow_dispatch
jobs:
  wheels-windows:
    runs-on: windows-2022
    strategy:
      matrix:
        include:
          - arch: AMD64
            platform: x64
            boost-lib: 64
          - arch: x86
            platform: Win32
            boost-lib: 32
    steps:
    - name: uninstall SWIG 4.1.1
      run: |
        choco uninstall swig
    - name: install SWIG (4.3.0)
      run: |
        curl -L -o swigwin-4.3.0.zip https://sourceforge.net/projects/swig/files/swigwin/swigwin-4.3.0/swigwin-4.3.0.zip
        pwd
        dir
        $currentFolder = (Get-Location).Path
        Expand-Archive -Path "$currentFolder\swigwin-4.3.0.zip" -DestinationPath C:\local
        cd C:\local\swigwin-4.3.0
        .\swig.exe -version
        echo "C:\local\swigwin-4.3.0" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"
        #$CurrentPATH = ([Environment]::GetEnvironmentVariable("PATH")).Split(";")
        #$NewPATH = ($CurrentPATH + "C:\local\swigwin-4.3.0") -Join ";"
        #[Environment]::SetEnvironmentVariable("PATH", $NewPath, [EnvironmentVariableTarget]::Machine) 
        swig -version
    - name: check
      run: |
        swig -version
        swig -help

         
